//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroDude.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MicroDudeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MicroDudeSettings defaultInstance = ((MicroDudeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MicroDudeSettings())));
        
        public static MicroDudeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AvrDudePath {
            get {
                return ((string)(this["AvrDudePath"]));
            }
            set {
                this["AvrDudePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoFlash {
            get {
                return ((bool)(this["AutoFlash"]));
            }
            set {
                this["AutoFlash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Programmer {
            get {
                return ((string)(this["Programmer"]));
            }
            set {
                this["Programmer"] = value;
            }
        }
    }
}
